AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Setup Logging Lambda Webhook
Resources:
  LoggingLambdaWebhookFilter:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: s3://bboe-lambda-code/logging-lambda-webhook/deployment-package.zip
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: !GetAtt LoggingLambdaWebhookRole.Arn
  LoggingLambdaWebhookRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: AppendToLogsPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: "*"
  LoggingLambdaWebhookUrlPermissions:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LoggingLambdaWebhookFilter
      Action: lambda:InvokeFunctionUrl
      Principal: "*"
      FunctionUrlAuthType: NONE
  LoggingLambdaWebhookUrl:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn: !Ref LoggingLambdaWebhookFilter
      AuthType: NONE
